[tool.black]
line-length = 110
target-version = ['py312']

[tool.flake8]
max-line-length = 110
per-file-ignores = '__init__.py:F401'
extend-ignore = 'E203'
exclude = [
    '.git',
    'cnn/__pycache__'
]
